# Generated by Django 6.0.2 on 2026-02-05 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("token_uri", models.TextField(blank=True, null=True)),
                ("client_id", models.TextField(blank=True, null=True)),
                ("client_secret", models.TextField(blank=True, null=True)),
                ("scopes", models.TextField(blank=True, null=True)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
                ("spreadsheet_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
