# Generated by Django 5.2.11 on 2026-02-25 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='invoices/pdfs/%Y/%m/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('EXTRACTION_FAILED', 'Extraction Failed'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('BOOKED', 'Booked')], default='PROCESSING', max_length=20)),
                ('current_approval_round', models.PositiveIntegerField(default=1)),
                ('approvals_obtained', models.PositiveIntegerField(default=0)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('description_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_rates', models.CharField(blank=True, max_length=50, null=True)),
                ('supply_type', models.CharField(blank=True, choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], max_length=20, null=True)),
                ('service_category', models.CharField(blank=True, choices=[('SERV_0', 'SERV_0'), ('SERV_9', 'SERV_9'), ('SERV_13', 'SERV_13'), ('SERV_24', 'SERV_24'), ('SERV_EX', 'SERV_EX')], max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('supplier_country', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_country_group', models.CharField(blank=True, choices=[('EE', 'Estonia'), ('EU_OTHER', 'EU (other)'), ('NON_EU', 'Non-EU')], max_length=20, null=True)),
                ('supplier_vat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_address', models.TextField(blank=True, null=True)),
                ('buyer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_country_group', models.CharField(blank=True, choices=[('EE', 'Estonia'), ('EU_OTHER', 'EU (other)'), ('NON_EU', 'Non-EU')], max_length=20, null=True)),
                ('buyer_vat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('llm_raw_response', models.JSONField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_invoices', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='organizations.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTION_COMPLETED', 'Extraction Completed'), ('EXTRACTION_FAILED', 'Extraction Failed'), ('FIELDS_EDITED', 'Fields Edited'), ('APPROVED', 'Approved'), ('EDIT_REQUESTED', 'Edit Requested'), ('BOOKED', 'Booked'), ('COMMENTED', 'Commented')], max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('EDIT_REQUESTED', 'Edit Requested')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_approvals',
                'constraints': [models.UniqueConstraint(fields=('invoice', 'user', 'round'), name='unique_approval_per_user_per_round')],
            },
        ),
    ]
