# Generated by Django 6.0.2 on 2026-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicesubmission",
            name="invoice_file",
            field=models.FileField(
                blank=True, null=True, upload_to="invoice_submissions/%Y/%m/%d/"
            ),
        ),
    ]
