# Generated by Django 5.2.11 on 2026-02-08 21:24

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_submission_export_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesubmission',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='invoice_submissions/%Y/%m/%d/'),
        ),
    ]
